package dev.fragmentrpc.codegen

import com.google.devtools.ksp.processing.*
import com.google.devtools.ksp.symbol.KSClassDeclaration
import com.google.devtools.ksp.symbol.KSAnnotated
import com.google.gson.Gson
import com.squareup.kotlinpoet.*
import java.io.File

data class Field(val name: String, val type: String, val optional: Boolean, val list: Boolean, val `object`: Boolean)
data class Model(val name: String, val schemaType: String, val language: String, val proto: Boolean, val fields: List<Field>)
data class Conversion(val from: Model, val to: Model)
data class Declaration(val language: String, val declaration: String, val kind: String, val packageName: String?, val name: String, val document: String, val operation: String)
data class Models(val models: List<Model>, val conversions: List<Conversion>, val declarations: List<Declaration>)

class FragmentProcessorProvider : SymbolProcessorProvider {
    override fun create(environment: SymbolProcessorEnvironment): SymbolProcessor = FragmentProcessor(environment)
}

class FragmentProcessor(private val environment: SymbolProcessorEnvironment) : SymbolProcessor {
    private var generated = false
    private val pkg = "dev.fragmentrpc.generated"

    override fun process(resolver: Resolver): List<KSAnnotated> {
        if (generated) return emptyList()
        val metadata = Gson().fromJson(File(environment.options.getValue("fragmentModels")).readText(), Models::class.java)
        val declarations = metadata.declarations.filter { it.language == "kotlin" }
        val annotated = listOf("GraphQLFragment", "GraphQLQuery").flatMap { marker ->
            resolver.getSymbolsWithAnnotation("dev.fragmentrpc.graphql.$marker").filterIsInstance<KSClassDeclaration>().toList()
        }
        if (annotated.isEmpty()) return emptyList()
        for (declaration in declarations) {
            val symbol = annotated.singleOrNull { it.qualifiedName?.asString() == "${declaration.packageName}.${declaration.declaration}" }
            if (symbol == null) {
                environment.logger.error("Missing GraphQL declaration ${declaration.declaration}; regenerate contracts")
                return emptyList()
            }
            val document = symbol.annotations.first { it.shortName.asString() in listOf("GraphQLFragment", "GraphQLQuery") }.arguments.single().value as String
            if (document != declaration.document) {
                environment.logger.error("Stale GraphQL contract for ${declaration.declaration}; regenerate contracts", symbol)
                return emptyList()
            }
        }
        val file = FileSpec.builder(pkg, "NativeFragments").addFileComment("Generated by KSP from embedded GraphQL declarations.")
        for (declaration in declarations.filter { it.kind == "query" }) {
            file.addTypeAlias(TypeAliasSpec.builder(declaration.name, protoType(declaration.operation + "Response")).build())
        }
        for (model in metadata.models.filter { it.language == "kotlin" && !it.proto }) {
            val constructor = FunSpec.constructorBuilder()
            val type = TypeSpec.classBuilder(model.name).addModifiers(KModifier.DATA)
            for (field in model.fields) {
                val fieldType = fieldType(field)
                constructor.addParameter(field.name, fieldType)
                type.addProperty(PropertySpec.builder(field.name, fieldType).initializer("%N", field.name).build())
            }
            file.addType(type.primaryConstructor(constructor.build()).build())
        }
        for ((from, to) in metadata.conversions.filter { it.from.language == "kotlin" }) {
            val body = CodeBlock.builder().add("return %T(\n", modelType(to)).indent()
            for (field in to.fields) {
                var value = "this.`${field.name}`"
                if (field.`object`) value += when {
                    field.list -> ".map { it.as${field.type}() }"
                    field.optional && !from.proto -> "?.as${field.type}()"
                    else -> ".as${field.type}()"
                }
                if (field.optional && from.proto) value = "if (this.has${field.name.replaceFirstChar { it.uppercase() }}()) $value else null"
                body.add("%N = %L,\n", field.name, value)
            }
            body.unindent().add(")\n")
            file.addFunction(FunSpec.builder("as${to.name}").receiver(modelType(from)).returns(modelType(to)).addCode(body.build()).build())
        }
        environment.codeGenerator.createNewFile(Dependencies(true, *resolver.getAllFiles().toList().toTypedArray()), pkg, "NativeFragments")
            .bufferedWriter().use { file.build().writeTo(it) }
        generated = true
        return emptyList()
    }

    private fun protoType(name: String) = ClassName("app.v1", "App", name)
    private fun modelType(model: Model) = if (model.proto) protoType(model.name) else ClassName(pkg, model.name)
    private fun fieldType(field: Field): TypeName {
        var type: TypeName = if (field.`object`) ClassName(pkg, field.type) else when (field.type) {
            "Int" -> INT
            "Float" -> DOUBLE
            "Boolean" -> BOOLEAN
            else -> STRING
        }
        if (field.list) type = LIST.parameterizedByType(type)
        return type.copy(nullable = field.optional)
    }
}

private fun ClassName.parameterizedByType(type: TypeName): TypeName =
    com.squareup.kotlinpoet.ParameterizedTypeName.Companion.run { parameterizedBy(type) }
