import { readFile, readdir, mkdir, writeFile, mkdtemp, rm, rename } from "node:fs/promises";
import { join, resolve } from "node:path";
import { tmpdir } from "node:os";
import { execFileSync } from "node:child_process";
import { compile, type ContractLock } from "./compile.js";
import { collectSources } from "./sources.js";
import { nativeModels, swiftModels } from "./native.js";

let previous: ContractLock | undefined;
try { previous = JSON.parse(await readFile("generated/schema.lock.json", "utf8")); }
catch (error) { if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error; }
const sources = await collectSources();
const output = compile(await readFile("schema.graphql", "utf8"), sources, previous);
const native = nativeModels(output, sources);
const stage = await mkdtemp(join(tmpdir(), "fragment-rpc-"));
try {
  await writeFile(join(stage, "app.proto"), output.proto);
  await writeFile(join(stage, "backend.proto"), await readFile("proto/backend.proto"));
  execFileSync(process.env.PROTOC ?? "protoc", [
    `--plugin=protoc-gen-es=${resolve("node_modules/.bin/protoc-gen-es")}`,
    `--proto_path=${stage}`, `--es_out=${stage}`, "--es_opt=target=ts,import_extension=js",
    `--descriptor_set_out=${join(stage, "api.binpb")}`, "--include_imports",
    "app.proto", "backend.proto",
  ], { stdio: "inherit" });
  const routes = `// Generated by npm run generate.\nimport { fromJson } from "@bufbuild/protobuf";\nimport type { ConnectRouter } from "@connectrpc/connect";\nimport { AppService, ${output.operations.map(o => o.name + "ResponseSchema").join(", ")} } from "./app_pb.js";\nimport { execute, type Resolvers } from "../server/execute.js";\nimport type { OperationPlan } from "../server/plan.js";\nimport plans from "./operations.json";\n\nexport function registerOperations(router: ConnectRouter, resolvers: Resolvers) {\n  router.service(AppService, {\n${output.operations.map((o,i) => `    ${o.name[0].toLowerCase() + o.name.slice(1)}: async (request, context) =>\n      fromJson(${o.name}ResponseSchema, await execute(plans[${i}] as OperationPlan, request, resolvers, context.signal)),`).join("\n")}\n  });\n}\n`;
  await writeFile(join(stage, "routes.ts"), routes);
  await writeFile(join(stage, "fragments.ts"), "// Generated from colocated fragments.\n" + output.fragmentTypes);
  await writeFile(join(stage, "native-models.json"), JSON.stringify(native, null, 2) + "\n");
  await writeFile(join(stage, "NativeFragments.swift"), swiftModels(native));
  await writeFile(join(stage, "operations.json"), JSON.stringify(output.operations, null, 2) + "\n");
  await writeFile(join(stage, "schema.lock.json"), JSON.stringify(output.lock, null, 2) + "\n");
  await mkdir("generated", { recursive: true });
  for (const file of await readdir(stage)) {
    const content = await readFile(join(stage, file));
    try { if ((await readFile(join("generated", file))).equals(content)) continue; }
    catch (error) { if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error; }
    // Each build owns its staging file, including simultaneous Xcode and Gradle builds.
    const temporary = join("generated", `${file}.${process.pid}.tmp`);
    await writeFile(temporary, content);
    await rename(temporary, join("generated", file));
  }
  console.log(`Generated ${output.operations.length} RPC methods from colocated fragments.`);
} finally {
  await rm(stage, { recursive: true, force: true });
}
